/**
 * Emit React source strings from a {@link ComponentPlan}: the `.tsx` component,
 * a co-located `.module.css` (css-modules mode), a `.stories.tsx`, and the
 * package barrel. Output is deterministic given the same plan.
 */
import type { ComponentPlan, ElementNode, GenerateOptions, StyleMode } from "./model.js";

const BANNER = "// AUTO-GENERATED by @aurelius/pipeline. Do not edit by hand.";
const CSS_BANNER = "/* AUTO-GENERATED by @aurelius/pipeline. Do not edit by hand. */";

type ResolvedOptions = Required<Pick<GenerateOptions, "styleMode" | "framework" | "assetPath">>;

/** Emit the `.tsx` component module. */
export function emitComponentTsx(plan: ComponentPlan, options: ResolvedOptions): string {
  const imports: string[] = [];
  if (options.framework === "next" && plan.elements.some((e) => e.kind === "image")) {
    imports.push(`import Image from "next/image";`);
  }
  if (options.styleMode === "css-modules") {
    imports.push(`import styles from "./${plan.name}.module.css";`);
  }

  const propsType = emitPropsType(plan);
  const signature = emitSignature(plan);
  const container = containerClass(plan, options.styleMode);
  const body = plan.elements
    .map((el) => `      ${renderElement(el, options.styleMode, options.framework)}`)
    .join("\n");

  const lines = [BANNER];
  if (imports.length > 0) lines.push("", ...imports);
  lines.push(
    "",
    propsType,
    "",
    `${signature} {`,
    "  return (",
    `    <section${container}>`,
    body,
    "    </section>",
    "  );",
    "}",
    "",
    `export default ${plan.name};`,
    "",
  );
  return lines.join("\n");
}

function emitPropsType(plan: ComponentPlan): string {
  if (plan.props.length === 0) return `export type ${plan.name}Props = Record<string, never>;`;
  const fields = plan.props.map((p) => `  ${p.name}?: string;`).join("\n");
  return `export type ${plan.name}Props = {\n${fields}\n};`;
}

function emitSignature(plan: ComponentPlan): string {
  if (plan.props.length === 0) return `export function ${plan.name}()`;
  const params = plan.props.map((p) => `  ${p.name} = ${JSON.stringify(p.default)},`).join("\n");
  return `export function ${plan.name}({\n${params}\n}: ${plan.name}Props)`;
}

function containerClass(plan: ComponentPlan, mode: StyleMode): string {
  return mode === "tailwind" ? ` className="${plan.layout.className}"` : ` className={styles.root}`;
}

function renderElement(el: ElementNode, mode: StyleMode, framework: string): string {
  const cls =
    mode === "tailwind"
      ? el.className
        ? ` className="${el.className}"`
        : ""
      : ` className={styles.${el.cssClass}}`;

  if (el.kind === "text") {
    return `<${el.tag}${cls}>{${el.propName}}</${el.tag}>`;
  }
  if (framework === "next" && el.tag === "Image") {
    return `<Image src={${el.propName}} alt={${el.altPropName}} width={${el.width}} height={${el.height}}${cls} />`;
  }
  return `<img src={${el.propName}} alt={${el.altPropName}}${cls} />`;
}

/** Emit the co-located CSS Modules stylesheet. */
export function emitComponentCss(plan: ComponentPlan): string {
  const lines = [CSS_BANNER];
  const root = plan.css["root"];
  if (root) lines.push(`.root {\n  ${root}\n}`);
  for (const el of plan.elements) {
    const body = plan.css[el.cssClass];
    if (body) lines.push(`.${el.cssClass} {\n  ${body}\n}`);
  }
  return `${lines.join("\n\n")}\n`;
}

/** Emit a Storybook story with extracted content as default args. */
export function emitStoriesTsx(plan: ComponentPlan): string {
  const args = plan.props.map((p) => `    ${p.name}: ${JSON.stringify(p.default)},`).join("\n");
  return [
    BANNER,
    `import type { Meta, StoryObj } from "@storybook/react";`,
    `import { ${plan.name} } from "./${plan.name}";`,
    "",
    `const meta = { component: ${plan.name}, title: "InDesign/${plan.name}" } satisfies Meta<typeof ${plan.name}>;`,
    "export default meta;",
    "",
    `export const Default: StoryObj<typeof ${plan.name}> = {`,
    plan.props.length > 0 ? `  args: {\n${args}\n  },` : "  args: {},",
    "};",
    "",
  ].join("\n");
}

/** Emit the package barrel re-exporting every component. */
export function emitIndexTs(componentNames: string[]): string {
  const exports = componentNames.map((name) => `export { ${name} } from "./${name}";`);
  return [BANNER, ...exports, ""].join("\n");
}
