/**
 * Serializers that turn {@link DesignTokens} into the four output artifacts:
 * `tokens.ts`, `tokens.css`, `tailwind.preset.ts`, and a Style Dictionary
 * compatible `design-tokens.json`.
 *
 * Every value in {@link DesignTokens} is already a string, so `JSON.stringify`
 * yields valid TypeScript object-literal syntax for the `.ts` outputs.
 */
import type { DesignTokens } from "./model.js";

const BANNER = "// AUTO-GENERATED by @aurelius/pipeline. Do not edit by hand.";

export interface EmitTsOptions {
  /**
   * When set, the generated `tokens.ts` imports `DesignTokens` from this module
   * specifier and asserts `satisfies DesignTokens`. When omitted, the file is
   * self-contained (`as const`) and depends on nothing.
   */
  typeImport?: string;
}

/** Emit a typed `tokens.ts` module. */
export function emitTokensTs(tokens: DesignTokens, options: EmitTsOptions = {}): string {
  const literal = JSON.stringify(tokens, null, 2);
  if (options.typeImport) {
    return [
      BANNER,
      `import type { DesignTokens } from "${options.typeImport}";`,
      "",
      `export const tokens = ${literal} satisfies DesignTokens;`,
      "",
      "export default tokens;",
      "",
    ].join("\n");
  }
  return [
    BANNER,
    `export const tokens = ${literal} as const;`,
    "",
    "export type DesignTokens = typeof tokens;",
    "",
    "export default tokens;",
    "",
  ].join("\n");
}

/** Emit CSS custom properties under `:root`. */
export function emitTokensCss(tokens: DesignTokens): string {
  const lines: string[] = [`${cssBanner()}`, ":root {"];
  const groups: Array<[string, Record<string, string>]> = [
    ["color", tokens.colors],
    ["font-family", tokens.fontFamilies],
    ["font-size", tokens.fontSizes],
    ["line-height", tokens.lineHeights],
    ["letter-spacing", tokens.letterSpacing],
    ["spacing", tokens.spacing],
  ];
  for (const [prefix, record] of groups) {
    for (const [key, value] of Object.entries(record)) {
      lines.push(`  --${prefix}-${key}: ${value};`);
    }
  }
  lines.push("}", "");
  return lines.join("\n");
}

/** A Tailwind `theme.extend` preset object exposing every token. */
export interface TailwindPreset {
  theme: {
    extend: {
      colors: Record<string, string>;
      fontFamily: Record<string, string>;
      fontSize: Record<string, string>;
      lineHeight: Record<string, string>;
      letterSpacing: Record<string, string>;
      spacing: Record<string, string>;
    };
  };
}

/** Build the Tailwind preset object (every token under `theme.extend`). */
export function buildTailwindPreset(tokens: DesignTokens): TailwindPreset {
  return {
    theme: {
      extend: {
        colors: tokens.colors,
        fontFamily: tokens.fontFamilies,
        fontSize: tokens.fontSizes,
        lineHeight: tokens.lineHeights,
        letterSpacing: tokens.letterSpacing,
        spacing: tokens.spacing,
      },
    },
  };
}

/** Emit a Tailwind v3+ preset module exposing every token under `theme.extend`. */
export function emitTailwindPreset(tokens: DesignTokens): string {
  const preset = buildTailwindPreset(tokens);
  return [
    BANNER,
    `const preset = ${JSON.stringify(preset, null, 2)};`,
    "",
    "export default preset;",
    "",
  ].join("\n");
}

/** Emit a Style Dictionary compatible token tree. */
export function emitStyleDictionaryJson(tokens: DesignTokens): string {
  const wrap = (record: Record<string, string>): Record<string, { value: string }> => {
    const out: Record<string, { value: string }> = {};
    for (const [key, value] of Object.entries(record)) out[key] = { value };
    return out;
  };
  const tree = {
    color: wrap(tokens.colors),
    font: { family: wrap(tokens.fontFamilies) },
    size: {
      font: wrap(tokens.fontSizes),
      lineHeight: wrap(tokens.lineHeights),
      letterSpacing: wrap(tokens.letterSpacing),
      spacing: wrap(tokens.spacing),
    },
  };
  return `${JSON.stringify(tree, null, 2)}\n`;
}

export interface EmitAllOptions extends EmitTsOptions {
  /** Include `tailwind.preset.ts` (default true). */
  tailwind?: boolean;
}

/** Produce all output artifacts as a `{ filename: contents }` map. */
export function emitAll(
  tokens: DesignTokens,
  options: EmitAllOptions = {},
): Record<string, string> {
  const files: Record<string, string> = {
    "tokens.ts": emitTokensTs(tokens, options),
    "tokens.css": emitTokensCss(tokens),
    "design-tokens.json": emitStyleDictionaryJson(tokens),
  };
  if (options.tailwind !== false) {
    files["tailwind.preset.ts"] = emitTailwindPreset(tokens);
  }
  return files;
}

function cssBanner(): string {
  return "/* AUTO-GENERATED by @aurelius/pipeline. Do not edit by hand. */";
}
